name: hamlet-schema-updater

on:
  push:
    branches:
      - "master"

jobs:
  hamlet-schema-updater:
    runs-on: ubuntu-latest
    container:
      image: hamletio/hamlet:latest
      volumes:
        - ${{ github.workspace }}:/home/hamlet/www

    steps:
      - name: Checkout Docs Site
        uses: actions/checkout@v2
      
      - name: Generate Hamlet Schemas
        uses: rossmurr4y/hamlet-go@v1
        with:
          task_build_schemas: true
          task_build_schemas_output: /github/workspace/docs/static/schema/latest/blueprint

      - name: Commit Schemas into Repo
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: publish latest hamlet schemas.
