name: hamlet-schema-updater

on:
  push:
    branches:
      - "master"

jobs:
  hamlet-schema-updater:
    runs-on: ubuntu-latest
    container:
      image: hamletio/hamlet:latest

    steps:
      - name: Checkout Docs Site
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
          path: /home/hamlet/www
      
      - name: Generate Hamlet Schemas
        run: |
          hamlet entrance -i mock -p aws -p awstest -p azure -p azuretest invoke-entrance -e schema -u component -o /home/hamlet/schema
          hamlet entrance -i mock -p aws -p awstest -p azure -p azuretest invoke-entrance -e schema -u reference -o  /home/hamlet/schema
          hamlet entrance -i mock -p aws -p awstest -p azure -p azuretest invoke-entrance -e schema -u metaparameter -o /home/hamlet/schema

      - name: Copy Schemas Into Docs Site
        run: |
          cp ~/schema/schema-component-schema.json /home/hamlet/www/docs/static/schema/latest/blueprint/component-schema.json
          cp ~/schema/schema-reference-schema.json /home/hamlet/www/docs/static/schema/latest/blueprint/reference-schema.json
          cp ~/schema/schema-meta-schema.json /home/hamlet/www/docs/static/schema/latest/blueprint/metaparameter-schema.json
          
      - name: Commit Schemas into Repo
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: publish latest hamlet schemas.
